### ISSUE TITLE
ERROR TypeError: this.dpElement.datetimepicker is not a function

### ISSUE THREAD

**Issue by george-vlahakis** [fetrarij/ng-tempusdominus-bootstrap4#3]
I am getting the above exception when I try to add the component in an existing project.

There is nothing in the docs that could assist me in resolving this.

Full stack:

`AppTestComponent.html:9 ERROR TypeError: this.dpElement.datetimepicker is not a function
    at NgTempusdominusBootstrapInputDirective.push../node_modules/ngx-tempusdominus-bootstrap/esm5/ngx-tempusdominus-bootstrap.js.NgTempusdominusBootstrapInputDirective.ngOnInit (ngx-tempusdominus-bootstrap.js:97)
    at checkAndUpdateDirectiveInline (core.js:9035)
    at checkAndUpdateNodeInline (core.js:10299)
    at checkAndUpdateNode (core.js:10261)
    at debugCheckAndUpdateNode (core.js:10894)
    at debugCheckDirectivesFn (core.js:10854)
    at Object.eval [as updateDirectives] (AppTestComponent.html:9)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:10846)
    at checkAndUpdateView (core.js:10243)
    at callViewAction (core.js:10484)`

Tried checking all packages and references but nothing sticks out as a problem at this point.

**Comment by fetrarij** [comment]
Hello, Did you already included jquery & tempus dominus ?
Do you use angular cli? If not give more detail on your environment.

**Comment by george-vlahakis** [comment]
Hi, thanks for the response.
jQuery is included (and used) in the project.
Tempus Dominus included as well (no compilation errors).

Note that we are also using 

Below the package.json contents:

> {
  "name": "trunk",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/animations": "6.0.9",
    "@angular/cli": "^6.0.8",
    "@angular/common": "6.0.9",
    "@angular/compiler": "6.0.9",
    "@angular/compiler-cli": "6.0.9",
    "@angular/core": "6.0.9",
    "@angular/forms": "6.0.9",
    "@angular/http": "6.0.9",
    "@angular/language-service": "6.0.9",
    "@angular/platform-browser": "6.0.9",
    "@angular/platform-browser-dynamic": "6.0.9",
    "@angular/router": "6.0.9",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.101",
    "angular-tree-component": "^7.0.1",
    "bootstrap": "^4.0.0",
    "codelyzer": "^4.4.2",
    "core-js": "^2.4.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "jquery": "^3.3.1",
    "jwt-decode": "^2.2.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.11",
    "ng-bootstrap": "^1.6.3",
    "ng-multiselect-dropdown": "^0.1.5",
    "ng2-cookies": "^1.0.12",
    "ng2-search-filter": "^0.4.7",
    "ngx-bootstrap": "^3.0.1",
    "ngx-order-pipe": "^2.0.1",
    "ngx-pagination": "^3.1.1",
    "ngx-tempusdominus-bootstrap": "^1.0.0",
    "popper.js": "latest",
    "protractor": "~5.1.2",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "tempusdominus-bootstrap-4": "^5.0.1",
    "tempusdominus-core": "^5.0.0",
    "ts-node": "~3.2.0",
    "tslint": "^5.11.0",
    "typescript": "2.7.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "angular-cli-ghpages": "^0.5.2",
    "font-awesome": "^4.7.0",
    "ng-packagr": "^2.4.4"
  }
}

And there are also the following entries in index.html 

> <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
>   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
>   <link href="assets/css/shared.css" rel="stylesheet">
>   <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
>   <link rel="stylesheet" href="https://unpkg.com/ngx-bootstrap/datepicker/bs-datepicker.css">
>   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
>   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/3.3.2/css/bootstrap3/bootstrap-switch.css">
>   <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
> </head>
> <body>
> 
>   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
>   <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
>   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
>   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
>   <script src="https://maps.googleapis.com/maps/api/js?client=gme-romexworldltd&libraries=drawing,geometry"></script>
>   <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
> 
>   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
>   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

In terms of modules, relevant code:

> import {BrowserModule} from '@angular/platform-browser';
> import {NgModule, Optional, SkipSelf} from '@angular/core';
> import {APP_BASE_HREF} from '@angular/common';
> import {RouterModule} from '@angular/router';
> import {HttpClientModule} from '@angular/common/http';
> import {CookieService} from 'ng2-cookies';
> import {NgTempusdominusBootstrapModule} from 'ngx-tempusdominus-bootstrap';
> import {BsDatepickerModule} from 'ngx-bootstrap';
> 
> @NgModule({
>   declarations: [
>     AppComponent,
>   ],
>   imports: [
>     ...
>     NgTempusdominusBootstrapModule,
>     BsDatepickerModule.forRoot(),
>     ...
>   ],
>   providers: [
>     ...
>   ],
>   bootstrap: [ ... ],
>   exports: [ ... ]
> })
> export class AppModule {
> 
>   constructor(@Optional() @SkipSelf() parentModule: AppModule) {
>     if (parentModule) {
>       throw new Error('AppModuleShared is already loaded.');
>     }
>   }
> 
> }
> 
> export function getBaseUrl() {
>   return document.getElementsByTagName('base')[0].href;
> }

**Comment by george-vlahakis** [comment]
FYI, I just confirmed that BsDatePicker is **not** causing the issue. Added it to your demo source and it still works fine.

**Comment by fetrarij** [comment]
I dont see where do you include the tempus dominus script and css. Should be in index.html like you do with jquery, bootstrap,..or in the angular-cli.json like the instruction at the readme.
Note that the ngxTempusDominus is just a wrapper and need the tempus dominus lib to be included first.

**Comment by george-vlahakis** [comment]
I am following your demo code to be honest and I cannot see any script and css includes relevant to the point made.

**Comment by fetrarij** [comment]
My demo code includes theses lib in angular.json at the main folder

**Comment by george-vlahakis** [comment]
Happy to report that adding the following in my angular.json fixes the issue! Many thanks for your support here!

```
      "styles": [
            "./node_modules/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.css",
            "src/styles.css"
      ],
      "scripts": [
            "./node_modules/moment/min/moment.min.js",
            "./node_modules/tempusdominus-bootstrap-4/build/js/tempusdominus-bootstrap-4.js"
      ]
```

**Comment by fetrarij** [comment]
Awesome. You should do the same for external lib like jquery, bootstrap,... not to including directly in index.html ;)

**Comment by george-vlahakis** [comment]
Good point and was wondering what the best way to do this is! Great!

Question (optional): in angular.json you can only include local files right? I mean to say not with full urls (ie Google Fonts) `<link href='https://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>`

**Comment by fetrarij** [comment]
for external lib, include them in index.html
