### ISSUE TITLE
Click button calendar

### ISSUE THREAD

**Issue by LuisAlejandroDuarte** [fetrarij/ng-tempusdominus-bootstrap4#9]
The following error appears when clicking on the button to view the calendar
![image](https://user-images.githubusercontent.com/9936927/90287246-0ff04f80-de3d-11ea-865d-84f8938d13e2.png)

I have the code as follows and I am using Angular 9

 <label>Fecha</label>
                            <div class="input-group date" data-target-input="nearest" NgTempusdominusBootstrap>
                                <input 
                                class="form-control form-control-sm"
                                [(ngModel)]="dateInline"                               
                                [options]="options"
                                NgTempusdominusBootstrapInput
                                type="text"/>
                                <div class="input-group-append" NgTempusdominusBootstrapToggle>
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>

If anyone knows this I would appreciate it, Thank you

@fetrarij

**Comment by jmmoyadev** [comment]
Same problem here!

**Comment by LuisAlejandroDuarte** [comment]
Hi @jmmoya  
The following error appears when clicking on the button to view the calendar

![image](https://user-images.githubusercontent.com/9936927/90648731-860b0280-e1ff-11ea-8c79-5b9fee57d5c9.png)

If anyone knows this I would appreciate it, Thank you

**Comment by LuisAlejandroDuarte** [comment]
> Same problem here!

Hi @jmmoya  
The following error appears when clicking on the button to view the calendar

![image](https://user-images.githubusercontent.com/9936927/90648731-860b0280-e1ff-11ea-8c79-5b9fee57d5c9.png)

If anyone knows this I would appreciate it, Thank you

**Comment by Eonasdan** [comment]
I put in a PR to fix this, if you're in a hurry it's about three lines of code to change. Copy/paste the directives directly into your project
